{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operyx.fullname" . }}-redis
  labels:
    {{- include "operyx.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "operyx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "operyx.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.service.redis.port }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "operyx.fullname" . }}-redis
  labels:
    {{- include "operyx.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - port: {{ .Values.service.redis.port }}
      targetPort: {{ .Values.service.redis.port }}
  selector:
    {{- include "operyx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
