apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operyx.fullname" . }}-secrets
  labels:
    {{- include "operyx.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  DATABASE_URL_SYNC: {{ .Values.secrets.databaseUrlSync | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
